baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "learn"

[params]
themeVariant = "walabs"
disableShortcutsTitle = true

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]
section = ["HTML","RSS"]
